-- CreateTable
CREATE TABLE `TraineeClassEarning` (
    `id` VARCHAR(191) NOT NULL,
    `attendanceCheckInId` VARCHAR(191) NOT NULL,
    `monthKey` VARCHAR(191) NOT NULL,
    `userMembershipId` VARCHAR(191) NULL,
    `bookingId` VARCHAR(191) NULL,
    `scheduleId` VARCHAR(191) NULL,
    `occurrenceKey` VARCHAR(191) NULL,
    `attendanceDate` DATE NOT NULL,
    `attendanceTime` VARCHAR(191) NULL,
    `customerId` VARCHAR(191) NOT NULL,
    `customerNameSnapshot` VARCHAR(191) NULL,
    `classId` VARCHAR(191) NULL,
    `classNameSnapshot` VARCHAR(191) NULL,
    `actualTrainerId` VARCHAR(191) NULL,
    `actualTrainerNameSnapshot` VARCHAR(191) NULL,
    `actualEmployeeId` VARCHAR(191) NULL,
    `actualEmployeeCodeSnapshot` VARCHAR(191) NULL,
    `actualEmployeeNameSnapshot` VARCHAR(191) NULL,
    `coachCompensationTermId` VARCHAR(191) NULL,
    `paymentAmountMinor` INTEGER NOT NULL DEFAULT 0,
    `totalSessionsSnapshot` INTEGER NULL,
    `entitlementUnitsSnapshot` INTEGER NULL,
    `unitValueMinor` INTEGER NOT NULL DEFAULT 0,
    `commissionBaseMinor` INTEGER NOT NULL DEFAULT 0,
    `commissionRateBps` INTEGER NULL,
    `commissionAmountMinor` INTEGER NOT NULL DEFAULT 0,
    `currency` VARCHAR(191) NOT NULL DEFAULT 'EGP',
    `status` VARCHAR(191) NOT NULL DEFAULT 'blocked',
    `blockReason` VARCHAR(191) NULL,
    `calculatedAt` DATETIME(3) NULL,
    `calculatedById` VARCHAR(191) NULL,
    `finalizedAt` DATETIME(3) NULL,
    `finalizedById` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `TraineeClassEarning_attendanceCheckInId_key`(`attendanceCheckInId`),
    INDEX `TraineeClassEarning_monthKey_status_idx`(`monthKey`, `status`),
    INDEX `TraineeClassEarning_actualEmployeeId_monthKey_idx`(`actualEmployeeId`, `monthKey`),
    INDEX `TraineeClassEarning_userMembershipId_idx`(`userMembershipId`),
    INDEX `TraineeClassEarning_bookingId_idx`(`bookingId`),
    INDEX `TraineeClassEarning_scheduleId_idx`(`scheduleId`),
    INDEX `TraineeClassEarning_occurrenceKey_idx`(`occurrenceKey`),
    INDEX `TraineeClassEarning_coachCompensationTermId_idx`(`coachCompensationTermId`),
    INDEX `TraineeClassEarning_calculatedById_idx`(`calculatedById`),
    INDEX `TraineeClassEarning_finalizedById_idx`(`finalizedById`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
