import { beforeEach, describe, expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}));
vi.mock("@/lib/db", () => ({ db: { paymentTransaction: { findUnique: vi.fn() }, userMembership: { findUnique: vi.fn() } } }));
vi.mock("@/lib/analytics/business-events", () => ({ recordBusinessAnalyticsEvent: vi.fn() }));
import { recordPaymentStatusEvent } from "@/lib/analytics/payment-events";
import { db } from "@/lib/db";
import { recordBusinessAnalyticsEvent } from "@/lib/analytics/business-events";
describe("payment analytics events", () => {
 beforeEach(() => { vi.clearAllMocks(); vi.mocked(db.paymentTransaction.findUnique).mockResolvedValue({ id:"tx",userId:"u",membershipId:"um",offerId:null,orderId:null,amount:55,currency:"EGP",paymentMethod:"paymob" } as never); vi.mocked(db.userMembership.findUnique).mockResolvedValue({ membership:{id:"m",name:"Plan",kind:"subscription"},offer:null } as never); });
 it("records paid using trusted transaction values", async()=>{ await recordPaymentStatusEvent("tx","paid"); expect(recordBusinessAnalyticsEvent).toHaveBeenCalledWith(expect.objectContaining({eventName:"payment_succeeded",value:55,currency:"EGP",entityType:"subscription",entityId:"m",paymentTransactionId:"tx",metadata:{paymentMethodType:"card"}})); });
 it.each([["wallet","wallet"],["cash","cash"],["installment","bnpl"],["mystery","unknown"]])("normalizes %s",async(method,kind)=>{ vi.mocked(db.paymentTransaction.findUnique).mockResolvedValue({id:"tx",userId:"u",membershipId:"um",offerId:null,orderId:null,amount:1,currency:"KWD",paymentMethod:method} as never); await recordPaymentStatusEvent("tx","paid"); expect(recordBusinessAnalyticsEvent).toHaveBeenCalledWith(expect.objectContaining({metadata:{paymentMethodType:kind}})); });
 it.each([["failed","unknown"],["cancelled","cancelled"],["expired","expired"]] as const)("records safe failure category",async(status,category)=>{ await recordPaymentStatusEvent("tx",status); expect(recordBusinessAnalyticsEvent).toHaveBeenCalledWith(expect.objectContaining({eventName:"payment_failed",metadata:{failureCategory:category}})); });
 it("uses offer, package and order relations rather than text",async()=>{ vi.mocked(db.userMembership.findUnique).mockResolvedValue({membership:{id:"p",name:"Package",kind:"package"},offer:{id:"o",title:"Offer"}} as never); vi.mocked(db.paymentTransaction.findUnique).mockResolvedValue({id:"tx",userId:"u",membershipId:"um",offerId:"o",orderId:null,amount:1,currency:"EGP",paymentMethod:"card"} as never); await recordPaymentStatusEvent("tx","paid"); expect(recordBusinessAnalyticsEvent).toHaveBeenCalledWith(expect.objectContaining({entityType:"offer",entityId:"o"})); vi.mocked(db.paymentTransaction.findUnique).mockResolvedValue({id:"tx",userId:"u",membershipId:null,offerId:null,orderId:"order",amount:1,currency:"EGP",paymentMethod:"card"} as never); await recordPaymentStatusEvent("tx","paid"); expect(recordBusinessAnalyticsEvent).toHaveBeenLastCalledWith(expect.objectContaining({entityType:"order",entityId:"order"})); });
 it("ignores missing entity and absorbs analytics failure",async()=>{ vi.mocked(db.userMembership.findUnique).mockResolvedValue(null); await expect(recordPaymentStatusEvent("tx","paid")).resolves.toBeUndefined(); expect(recordBusinessAnalyticsEvent).not.toHaveBeenCalled(); });
});
